FROM ruby:3.0.2

# Set default locale for the environment
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \ 
    build-essential \
    ruby-full \
    zlib1g-dev

COPY Gemfile Gemfile.lock jekyll-text-theme.gemspec ./

RUN gem install sass-embedded -v '1.63.3' --source https://rubygems.org/
RUN gem install jekyll bundler
RUN bundle install

EXPOSE 4000

CMD ["bundle", "exec", "jekyll", "serve"]
